name: 构建预览并部署到 Netlify

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: 构建
    runs-on: ubuntu-22.04
    environment:
      name: 预览 Preview
      url: ${{ steps.netlify-deployment.outputs.NETLIFY_URL }}
    permissions:
      pull-requests: write
    steps:
      - name: 搜索评论 ID
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 到 Netlify

      - name: 创建或更新评论
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🚧 正在部署到 Netlify

            | 状态         | URL                                  |
            |-------------|--------------------------------------|
            | 等待中       | `部署完成后将会在此处更新 URL`           |
          edit-mode: replace

      - name: 签出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: false
          version: 9

      - name: 获取 pnpm store 目录
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: 配置 pnpm 缓存
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 安装思源黑体
        run: |
          mkdir -p ~/.local/share/fonts
          cp public/source-han-sans.ttf ~/.local/share/fonts/source-han-sans.ttf

      - name: 构建
        run: pnpm docs:build

      - name: 安装 Netlify CLI
        run: pnpm install -g netlify-cli

      - name: 推送到 Netlify
        id: netlify
        timeout-minutes: 10
        run: |
          NETLIFY_JSON_OUTPUT=$(netlify deploy --dir .vitepress/dist --json)
          echo $NETLIFY_JSON_OUTPUT
          echo "NETLIFY_JSON_OUTPUT=$(echo $NETLIFY_JSON_OUTPUT)" >> $GITHUB_ENV
          echo "NETLIFY_URL=$(echo $NETLIFY_JSON_OUTPUT | jq -r .deploy_url)" >> $GITHUB_ENV
          cat $GITHUB_ENV
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: 创建或更新评论
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ✅ 已成功部署到 Netlify

            | 状态        | URL                                                 |
            |-------------|-----------------------------------------------------|
            | 成功         | ${{ env.NETLIFY_URL }} |
          edit-mode: replace

